servo: Merge #13634 - Blind attempt to fix #13626 (from servo:bind-attempt-at-windows-fix); r=Ms2ger
<!-- Please describe your changes on the following line: -->

The error message was:

```
error: unknown character escape: d
  --> C:\projects\servo\target\debug\build\style-9b556a6c7bb4f044\out/properties.rs:44:55
   |
44 | #[path="C:/projects/servo/components/style/properties\declaration_block.rs"]
   |
```

Use `repr()` to get a Python string literal (whose character escaping is compatible enough with Rust’s) and `[1:-1]` to remove the single quotes.

---
<!-- Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data: -->
- [x] `./mach build -d` does not report any errors
- [x] `./mach test-tidy` does not report any errors
- [x] These changes fix #13626 (github issue number if applicable).

<!-- Either: -->
- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

<!-- Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process. -->

Source-Repo: https://github.com/servo/servo
Source-Revision: 86f31d0dc7d94f5c836380e22f2cdf0411dcb2a1