servo: Merge #10585 - Rust upgrade to 2016-04-12 (from servo:rustup_20160414); r=Ms2ger
This currently spews out a ton of ld errors of the form

```
/home/manishearth/Mozilla/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jit/JitFrameIterator.h:455: error: undefined reference to 'js::jit::SnapshotReader::readAllocation()'
```

cc @nox

Source-Repo: https://github.com/servo/servo
Source-Revision: 3b96bba1d523f9b8c01581a7004f1bdd04a11f73